name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Format
      run: cargo fmt --check
    - name: Clippy
      run: cargo clippy && cargo clippy --all-features
    - name: Build
      run: cargo build --verbose --all-features
    - name: Doc
      run: cargo doc --all-features
    - name: Cargo test
      run: sudo -E env "PATH=$PATH" cargo test --tests --features tokio
